# -*- coding: utf-8 -*-

"""
    predix

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from .api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # An enum for SDK environments
    class Environment(object):
        PRODUCTION = 0

    # An enum for API servers
    class Server(object):
        SERVER_1 = 0
        SERVER_2 = 1
        SERVER_3 = 2

    # The environment in which the SDK is running
    environment = Environment.PRODUCTION

    # TODO: Set an appropriate value
    username = None

    # TODO: Set an appropriate value
    password = None


    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.SERVER_1: 'https://f3f97f89-3574-4a9f-a870-906676e63cc8.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth',
            Server.SERVER_2: 'https://756f1541-2739-4720-ae20-535c4c96e056.run.aws-usw02-pr.ice.predix.io/api/v1/analytic',
            Server.SERVER_3: 'https://e104cb9a-86c1-4ae6-ac8b-afd66e1b3c8d.run.aws-usw02-pr.ice.predix.io/api/v1/analytic',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.SERVER_1):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        return cls.environments[cls.environment][server]
