# -*- coding: utf-8 -*-

"""
    predix

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from .decorators import lazy_property
from .configuration import Configuration
from .controllers.api_controller import APIController

class PredixClient(object):

    config = Configuration

    @lazy_property
    def client(self):
        return APIController()


    def __init__(self, 
                 username = None,
                 password = None):
        if username != None:
            Configuration.username = username
        if password != None:
            Configuration.password = password


