# -*- coding: utf-8 -*-

"""
    predix

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class SynchronousExecutionPredictResolutionsRequest(object):

    """Implementation of the 'Synchronous Execution- Predict ResolutionsRequest' model.

    TODO: type model description here.

    Attributes:
        symptoms (string): TODO: type description here.
        errors (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "symptoms":'symptoms',
        "errors":'errors'
    }

    def __init__(self,
                 symptoms=None,
                 errors=None):
        """Constructor for the SynchronousExecutionPredictResolutionsRequest class"""

        # Initialize members of the class
        self.symptoms = symptoms
        self.errors = errors


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        symptoms = dictionary.get('symptoms')
        errors = dictionary.get('errors')

        # Return an object of this model
        return cls(symptoms,
                   errors)


