# -*- coding: utf-8 -*-

"""
    predix

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class SynchronousExecutionNLPRequest(object):

    """Implementation of the 'Synchronous Execution- NLPRequest' model.

    TODO: type model description here.

    Attributes:
        input_text (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "input_text":'input_text'
    }

    def __init__(self,
                 input_text=None):
        """Constructor for the SynchronousExecutionNLPRequest class"""

        # Initialize members of the class
        self.input_text = input_text


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        input_text = dictionary.get('input_text')

        # Return an object of this model
        return cls(input_text)


